name: Create UDS Package
description: Creates a UDS package for the requested path

inputs:
  working-dir:
    description: Zarf package path
    required: true
  download-init-package: 
    description: Include Zarf init package
    required: false

runs:
  using: composite
  steps:
    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@main
      with:
        # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
        version: v0.27.1
        download-init-package: ${{ inputs.download-init-package }}

    - name: Create Zarf Package
      shell: bash
      run: zarf package create --confirm
      working-directory: ${{ inputs.working-dir }}
